export { getHederaClient, checkHederaConnection } from './client'
export { createVaultAuditTopic, setActiveTopic, getActiveTopicId, logToHCS } from './hcs-logger'
export { createVaultToken, mintVaultShares } from './hts-vault'
export { registerAgentIdentity } from './agent-identity'
export { payForAgentCycle } from './agent-payment'
export { getAuditLogs, getTokenInfo as getHederaTokenInfo, getAccountBalance, getTopicInfo } from './mirror-node'
export { scheduleVaultOperation, getScheduleStatus } from './scheduler'
export { initHederaVault } from './vault-init'
