export { ensPublicClient, ensWalletClient, ENS_PUBLIC_RESOLVER, ENS_BASE_DOMAIN } from './client'
export { slugify, buildEnsName, createVaultSubname, readTextRecord, setTextRecord, batchSetTextRecords } from './subname'
export type { SubnameResult } from './subname'
export { computePolicyHash, commitPolicyHash, verifyPolicyIntegrity } from './policy-commitment'
export type { PolicyVerificationResult } from './policy-commitment'
export { updateAgentStats, readAgentStats } from './agent-stats'
export type { AgentStats } from './agent-stats'
export { registerAgentENSIP25, verifyAgentIdentity, resolveAgentProfile } from './agent-identity'
export { registerAgentInFleet, getFleetAgents, updateFleetAgentStatus } from './fleet-registry'
export type { FleetAgent } from './fleet-registry'
export { writeVaultMetadata } from './vault-metadata'
export type { VaultMetadata } from './vault-metadata'
export { initVaultENS, buildEnsContext } from './vault-ens-init'
export type { ENSInitResult } from './vault-ens-init'
