use schemars::JsonSchema;
use serde::Deserialize;

/// Maximum accepted length for a vault_id. Vault IDs are generated UUIDs (~36
/// chars); anything dramatically longer is rejected to bound resource use and
/// reject obvious injection / misuse. Applied via [`validate_vault_id`].
pub const MAX_VAULT_ID_LEN: usize = 128;

/// Hard cap on the number of rows a listing tool (`get_recent_outcomes`,
/// `get_pnl`, `get_audit`) will return. Consumer-supplied `limit` values are
/// clamped to this in [`clamp_limit`] so a huge value cannot OOM the process.
pub const MAX_LIMIT: u32 = 500;

/// Maximum number of characters accepted for active guidance text. Guidance is
/// injected verbatim into the trading AI's prompt each cycle, so it must stay
/// short and is capped to blunt prompt-injection payloads.
pub const MAX_GUIDANCE_LEN: usize = 2000;

/// Validate a consumer-supplied vault_id: non-empty, within [`MAX_VAULT_ID_LEN`].
/// Returns an error message suitable for an MCP `invalid_params` response when
/// the value is rejected. UUIDs generated by `create_vault` always pass; this
/// guards the ~16 tools that accept an externally supplied id.
pub fn validate_vault_id(vault_id: &str) -> Result<(), String> {
    if vault_id.trim().is_empty() {
        return Err("vault_id must not be empty".to_string());
    }
    if vault_id.len() > MAX_VAULT_ID_LEN {
        return Err(format!(
            "vault_id exceeds max length of {} characters",
            MAX_VAULT_ID_LEN
        ));
    }
    Ok(())
}

/// Clamp a consumer-supplied listing `limit` to a safe upper bound
/// ([`MAX_LIMIT`]). Prevents a value like `u32::MAX` from asking Postgres to
/// materialize billions of rows.
pub fn clamp_limit(limit: Option<u32>, default: u32) -> i64 {
    limit.unwrap_or(default).min(MAX_LIMIT) as i64
}

/// Sanitize guidance text before it is persisted and injected into the trading
/// AI's prompt. Strips ASCII control characters (keep tab/newline/carriage
/// return so legitimate multi-line rules survive) and rejects payloads longer
/// than [`MAX_GUIDANCE_LEN`]. Returns `(sanitized, error_message?)`.
pub fn sanitize_guidance(guidance: &str) -> (String, Option<String>) {
    if guidance.len() > MAX_GUIDANCE_LEN {
        return (
            String::new(),
            Some(format!(
                "guidance exceeds max length of {} characters",
                MAX_GUIDANCE_LEN
            )),
        );
    }
    let sanitized: String = guidance
        .chars()
        .filter(|&c| c == '\t' || c == '\n' || c == '\r' || !c.is_control())
        .collect();
    (sanitized, None)
}

/// Validate a USDC withdrawal amount expressed as a decimal string (as used by
/// the on-chain transfer call). Rejects empty / negative / non-numeric values
/// at the tool boundary rather than letting them fail deep in the RPC call.
pub fn validate_amount(amount: &str) -> Result<(), String> {
    let trimmed = amount.trim();
    if trimmed.is_empty() {
        return Err("amount must not be empty".to_string());
    }
    // Accept an optional decimal number with up to 6 decimals (USDC precision).
    let parsed = trimmed
        .parse::<f64>()
        .map_err(|_| format!("amount is not a valid number: {:?}", trimmed))?;
    if !parsed.is_finite() {
        return Err("amount must be a finite number".to_string());
    }
    if parsed < 0.0 {
        return Err("amount must not be negative".to_string());
    }
    Ok(())
}

/// Validate an EVM recipient address: must be a 0x-prefixed hex string of 40
/// hex digits (20 bytes). Checksum (EIP-55) validation is intentionally NOT
/// performed here (providers accept both checksummed and lowercase forms), but
/// structural validity is enforced so an obviously malformed value fails at the
/// tool boundary instead of wasting an RPC round-trip.
pub fn validate_recipient(recipient: &str) -> Result<(), String> {
    let s = recipient.trim();
    if s.len() != 42 || !s.starts_with("0x") && !s.starts_with("0X") {
        return Err("recipient must be a 0x-prefixed 20-byte address (42 chars)".to_string());
    }
    let hex_part = &s[2..];
    if !hex_part.chars().all(|c| c.is_ascii_hexdigit()) {
        return Err("recipient contains non-hex characters after 0x prefix".to_string());
    }
    Ok(())
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct VaultIdParams {
    /// The vault ID
    pub vault_id: String,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct VaultLimitParams {
    /// The vault ID
    pub vault_id: String,
    /// Maximum number of records to return (default 100)
    #[serde(default)]
    pub limit: Option<u32>,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct CreateVaultParams {
    /// Vault name
    #[serde(default)]
    pub name: Option<String>,
    /// Wallet address
    #[serde(default)]
    pub wallet_address: Option<String>,
    /// Strategy configuration as JSON object
    #[serde(default)]
    pub strategy: Option<serde_json::Value>,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct UpdateConfigParams {
    /// The vault ID to update
    pub vault_id: String,
    /// Whether the strategy is enabled
    #[serde(default)]
    pub enabled: Option<bool>,
    /// Entry (bid) price in USDC
    #[serde(default)]
    pub entry_price: Option<f32>,
    /// Exit (ask) price in USDC
    #[serde(default)]
    pub exit_price: Option<f32>,
    /// Order size in units
    #[serde(default)]
    pub order_size: Option<i32>,
    /// Maximum capital in USDC
    #[serde(default)]
    pub max_capital_usdc: Option<f32>,
    /// Maximum trades per market
    #[serde(default)]
    pub max_trades_per_market: Option<i32>,
    /// Policy for max trades: "side" or "total"
    #[serde(default)]
    pub max_trades_policy: Option<String>,
    /// Seconds before expiry to stop new entries
    #[serde(default)]
    pub no_new_entries_last_seconds: Option<i32>,
    /// Seconds to keep sell orders after expiry
    #[serde(default)]
    pub keep_sell_orders_after_expiry_seconds: Option<i32>,
    /// Reconcile every N cycles
    #[serde(default)]
    pub reconcile_interval_cycles: Option<i32>,
    /// Minimum spread required
    #[serde(default)]
    pub min_spread_required: Option<f32>,
    /// Only allow passive (maker) orders
    #[serde(default)]
    pub strict_passive_only: Option<bool>,
    /// Allow placing bids on both sides
    #[serde(default)]
    pub allow_both_sides: Option<bool>,
    /// Cancel open buy orders near expiry
    #[serde(default)]
    pub cancel_open_buys_on_expiry: Option<bool>,
    /// Auto re-enter after cycle completes
    #[serde(default)]
    pub auto_reentry_enabled: Option<bool>,
    /// Maximum drawdown in USDC before stopping
    #[serde(default)]
    pub max_drawdown_usdc: Option<f32>,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct WithdrawParams {
    /// The vault ID to withdraw from
    pub vault_id: String,
    /// Recipient address to receive USDC
    pub recipient: String,
    /// Amount in USDC to withdraw
    pub amount: String,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct GuidanceParams {
    /// The vault ID to set guidance for
    pub vault_id: String,
    /// Contextual guidance text for the engine's AI. Empty string clears it.
    /// Keep to one or two concrete, actionable rules the model can heed.
    /// Capped at 2000 chars; ASCII control characters are stripped to blunt
    /// prompt-injection payloads before the text is injected into the AI prompt.
    pub guidance: String,
}
